version: "3"

# starts 2 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    image: minio/minio:RELEASE.2021-08-05T22-01-19Z
    command: server --console-address ":9008" http://minio{1...2}/data{1...2}
    expose:
      - "9007"
      - "9008"
    env_file:
      - ./minio.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio1
    volumes:
      - ./data/data1-1:/data1
      - ./data/data1-2:/data2

  minio2:
    image: minio/minio:RELEASE.2021-08-05T22-01-19Z
    command: server --console-address ":9008" http://minio{1...2}/data{1...2}
    expose:
      - "9007"
      - "9008"
    env_file:
      - ./minio.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio2
    volumes:
      - ./data/data2-1:/data1
      - ./data/data2-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9007:9000"
      - "9008:9001"
    depends_on:
      - minio1
      - minio2

